### ISSUE TITLE
Should there be container logs?

### ISSUE THREAD

**Issue by bbrala** [alekitto/sentry-kubernetes#1]
When deploying this as a helm, the conatiner seems to start fine, but it would be nice to see some logs. It seems like nothing is sent to sentry, but i cannot really see why.

**Comment by alekitto** [comment]
Hi @bbrala!
You can try to deploy the chart setting `sentry.logLevel` value to `debug`. Some details should appear in the container logs.

Maybe I should update the README files to explain it...

**Comment by bbrala** [comment]
Hehe, that would help probably. First thought that was the level for what gets send, but that's not true. :)

**Comment by bbrala** [comment]
And ty, I'll try that

**Comment by bbrala** [comment]
Well, it seems to process events, they are just not really being recieved at sentry.io, i've triple checked the dsn.

Is there some gotschas in how to configure the project in sentry?

**Comment by bbrala** [comment]
Ok it seems i did just receive an event from one of the clusters, ill keep an eye out if it keeps sending.

**Comment by bbrala** [comment]
Hmm, this should be reported by default right? But seems it isnt.

![image](https://github.com/alekitto/sentry-kubernetes/assets/3294970/a6ee9abf-2dde-4a26-9f57-631ba6689ef6)

Its a  warning, which is mentiones as being in the edfault filters.

**Comment by alekitto** [comment]
Yes, it should be reported with default filters. Can you post the debug logs from the container?

**Comment by bbrala** [comment]
https://gist.github.com/bbrala/2ab5d713ada48e020002480a557f3b05

**Comment by bbrala** [comment]
[sentry-kubernetes.log](https://github.com/alekitto/sentry-kubernetes/files/12323119/sentry-kubernetes.log)

**Comment by alekitto** [comment]
Could you please try the latest version?
If it's still not working could you try with `trace` debug log? It's very verbose, but should help a lot

**Comment by bbrala** [comment]
After reloading to newest image:

```
error killing pod: failed to "KillContainer" for "sentry-kubernetes" with KillContainerError: "rpc error: code = Unknown desc = Error response from daemon: No such container: c3719248148b3b53d8bd0c2170819e074a73cec97d749be019e92d1801e500a3"
```

So seems like it is sending more, ill keep an seye out. Thanks

**Comment by alekitto** [comment]
Marking this issue as resolved
Feel free to reopen it if you're noticing something wrong
